networks:
  movementor:
      name: movementor
      driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - movementor
    ports:
      - 5433:5432
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    image: backend
    networks:
      - movementor
    ports: 
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development

volumes:
  postgres-volume:      