services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - fullstack-network
    ports:
      - 5433:5432
    env_file:
      - .env.development
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    image: fullstack/backend
    networks:
      - fullstack-network
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env.development

networks:
  fullstack-network:
    name: fullstack-network
    driver: bridge

volumes:
  postgres-volume:
