services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env.test

  node:
    container_name: node
    build: .
    image: fullstack/backend
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env.test