name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "root"
          envkey_POSTGRES_HOST: "postgres"
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_DB: "movementor_test"
          envkey_JWT_SECRET: "top_secret"
          envkey_DATABASE_URL: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
          file_name: .env.test
      - name: Run tests
        run: docker compose -f docker-compose-test.yml run node npm run test